#!/usr/bin/env bash
#

PROGNAME="${0}"
PROGNAME="$(basename "${PROGNAME}")"

# Internationalization fix
# Bug: https://github.com/h0m3/autorandr-ui/issues/4
TEXTDOMAIN=yad
TEXTDOMAINDIR=/usr/share/locale


function info() {
    echo "${PROGNAME}: $1" >&1
}


function warning() {
    echo "${PROGNAME}: $1" >&2
}


function notification() {
    yad \
        --notification \
        --text="${1} Graphics detected" \
        --no-middle \
        --image="${1}"
}

function close_icon() {
    yad \
        --title="Close icon?"\
        --text="Do you want to close the icon from the screen"\
        --image="dialog-question"\
        --window-icon="dialog-question"\
        --button="yad-yes:0"\
        --button="yad-no:1"
}

close_icon

vendor="$(glxinfo | grep "OpenGL vendor string" | cut -d ":" -f 2)"

if echo "${vendor}" | grep "AMD" 2>&1 > /dev/null; then
    info "AMD graphics card detected"
    notification "amd"
elif echo "${vendor}" | grep "NVIDIA" 2>&1 > /dev/null; then
    info "NVIDIA graphics card detected"
    notification "nvidia"
else
    warning "No GPU detected"
    notification "yad-question"
fi
